apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
            labels:
              group: 'production'
      - job_name: 'grafana'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:3000']
            labels:
              group: 'production'
