---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000