---
 apiVersion: v1
 kind: Service
 metadata:
   name: my-first-service
   
 spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      name: grafana
      port: 3000
      targetPort: 3000
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: 9090
      
