---
 apiVersion: v1
 kind: Service
 metadata:
   name: my-service
   
 spec:
  type: LoadBalancer
  externalIPs:
  - 8.8.8.8 # fictional
  selector:
    app: my-app
  ports:
    - protocol: TCP
      name: grafana
      targetPort: 3000
      port: 3000
    - protocol: TCP
      name: prometheus
      targetPort: 9090
      port: 9090
      
