---
 apiVersion: v1
 kind: Service
 metadata:
   name: my-service
   
 spec:
  type: NodePort
  externalIPs:
  - 35.196.26.65
  selector:
    app: my-app
  ports:
    - protocol: TCP
      name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30003
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30009
      